#!/usr/bin/env bash
#This script ensures Nginx is installed, configured to listen on port 80, and running.

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
